
---
- name: Collect Tunnel Details
  hosts: iosxe_routers
  gather_facts: no
  connection: network_cli

  vars:
    report_file: "/tmp/tunnel_mtu_report.csv"
    default_mtu: 1476   # Fallback MTU if not found

  tasks:
    - name: Get Tunnel configs
      ios_command:
        commands:
          - show running-config | section interface Tunnel
      register: tunnel_config

    - name: Use raw config for parsing (skip split/join)
      set_fact:
        filtered_config: "{{ tunnel_config.stdout[0] }}"

    - name: Debug filtered config
      debug:
        var: filtered_config

    - name: Get Tunnel IPs
      ios_command:
        commands:
          - show ip interface brief | include Tunnel
      register: tunnel_ips

    - name: Debug tunnel IP output
      debug:
        var: tunnel_ips.stdout[0]

    - name: Parse Tunnel details (flexible regex)
      set_fact:
        tunnel_info: >-
          {{
            filtered_config | regex_findall(
              'interface Tunnel(\\d+)[\\s\\S]*?(?:ip mtu (\\d+))?[\\s\\S]*?(?:ip vrf forwarding (\\S+))?[\\s\\S]*?tunnel source (\\S+)[\\s\\S]*?tunnel destination (\\S+)'
            )
          }}

    - name: Debug parsed tunnel_info
      debug:
        var: tunnel_info

    - name: Parse Tunnel IPs
      set_fact:
        tunnel_ip_map: >-
          {{
            tunnel_ips.stdout[0] | regex_findall('Tunnel(\\d+)\\s+(\\S+)')
          }}

    - name: Debug parsed tunnel_ip_map
      debug:
        var: tunnel_ip_map

    - name: Combine Tunnel data and apply default MTU
      set_fact:
        device_tunnels: >-
          {{
            tunnel_info | map('list') | list
            | map('map', 'default', '') | list
            | map('map', 'zip', ['id','mtu','vrf','src','dst']) | list
            | map('map', 'combine') | list
            | map('map', 'combine', {'mtu': default_mtu}, attribute='mtu') | list
            | zip(tunnel_ip_map) | map('flatten') | list
          }}

    - name: Debug combined device_tunnels
      debug:
        var: device_tunnels

    - name: Save device tunnel info to localhost
      add_host:
        name: localhost
        all_tunnels: "{{ (hostvars['localhost'].all_tunnels | default([])) + [{'device': inventory_hostname, 'tunnels': device_tunnels}] }}"

- name: Validate MTUs and Ping
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Debug all_tunnels before processing
      debug:
        var: hostvars['localhost'].all_tunnels

    - name: Initialize report data
      set_fact:
        report_rows: []

    - name: Build tunnel pairs safely
      set_fact:
        tunnel_pairs: "{{ hostvars['localhost'].all_tunnels | community.general.json_query('[].tunnels[]') | default([]) | list }}"

    - name: Debug tunnel_pairs
      debug:
        var: tunnel_pairs

    - name: Find remote tunnel
      set_fact:
        remote_tunnel: "{{ tunnel_pairs | selectattr('3', 'equalto', item.1[4]) | list | first }}"
      loop: "{{ hostvars['localhost'].all_tunnels | subelements('tunnels') | default([]) }}"
      loop_control:
        label: "{{ item.0.device }} Tunnel {{ item.1[0] }}"
      vars:
        device: "{{ item.0.device }}"
        tunnel: "{{ item.1 }}"
      when: item.1 | length > 0

    - name: Run ping test
      ios_command:
        commands:
          - >-
            {% if tunnel[2] is defined %}
            ping vrf {{ tunnel[2] }} {{ remote_tunnel[5] }} size {{ tunnel[1]|default(default_mtu) }} df-bit repeat 5
            {% else %}
            ping {{ remote_tunnel[5] }} size {{ tunnel[1]|default(default_mtu) }} df-bit repeat 5
            {% endif %}
      delegate_to: "{{ device }}"
      register: ping_result
      when: remote_tunnel is defined
      loop: "{{ hostvars['localhost'].all_tunnels | subelements('tunnels') | default([]) }}"
      loop_control:
        label: "{{ item.0.device }} Tunnel {{ item.1[0] }}"
      vars:
        device: "{{ item.0.device }}"
        tunnel: "{{ item.1 }}"

    - name: Append row to report
      set_fact:
        report_rows: "{{ report_rows + [ {
          'device': device,
          'tunnel_id': tunnel[0],
          'local_mtu': tunnel[1]|default(default_mtu),
          'local_vrf': tunnel[2]|default('none'),
          'remote_device': remote_tunnel[6]|default('Not Found'),
          'remote_tunnel_id': remote_tunnel[0]|default('N/A'),
          'remote_mtu': remote_tunnel[1]|default('N/A'),
          'remote_vrf': remote_tunnel[2]|default('none'),
          'mtu_match': 'Yes' if tunnel[1]|default(default_mtu) == remote_tunnel[1]|default(default_mtu) else 'No',
          'ping_result': (ping_result.stdout[0] is defined and 'Success rate is 100 percent' in ping_result.stdout[0]) | ternary('Pass','Fail')
        }] }}"
      loop: "{{ hostvars['localhost'].all_tunnels | subelements('tunnels') | default([]) }}"
      loop_control:
        label: "{{ item.0.device }} Tunnel {{ item.1[0] }}"
      vars:
        device: "{{ item.0.device }}"
        tunnel: "{{ item.1 }}"
      when: item.1 | length > 0

    - name: Render CSV report
      template:
        src: tunnel_report.j2
        dest: "{{ report_file }}"
