
---
- name: Collect Tunnel Details
  hosts: iosxe_routers
  gather_facts: no
  connection: network_cli

  vars:
    report_file: "/tmp/tunnel_mtu_report.csv"

  tasks:
    - name: Get Tunnel configs
      ios_command:
        commands:
          - show running-config | section interface Tunnel
      register: tunnel_config

    - name: Filter out DMVPN tunnels
      set_fact:
        filtered_config: "{{ tunnel_config.stdout[0].split('\ninterface ') | reject('search', 'tunnel mode gre multipoint') | map('regex_replace', '^', 'interface ') | join('\n') }}"

    - name: Get Tunnel IPs
      ios_command:
        commands:
          - show ip interface brief | include Tunnel
      register: tunnel_ips

    - name: Parse Tunnel details
      set_fact:
        tunnel_info: >-
          {{
            filtered_config | regex_findall(
              'interface Tunnel(\\d+)\\n(?: .+\\n)*?ip mtu (\\d+)(?:\\n vrf forwarding (\\S+))?.*?tunnel source (\\S+).*?tunnel destination (\\S+)'
            )
          }}

    - name: Parse Tunnel IPs
      set_fact:
        tunnel_ip_map: >-
          {{
            tunnel_ips.stdout[0] | regex_findall('Tunnel(\\d+)\\s+(\\S+)')
          }}

    - name: Combine Tunnel data
      set_fact:
        device_tunnels: >-
          {{
            tunnel_info | map('list') | list | zip(tunnel_ip_map) | map('flatten') | list
          }}

    - name: Save device tunnel info
      set_fact:
        all_tunnels: "{{ (hostvars.localhost.all_tunnels | default([])) + [{'device': inventory_hostname, 'tunnels': device_tunnels}] }}"
      delegate_to: localhost

- name: Validate MTUs and Ping
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Initialize report data
      set_fact:
        report_rows: []

    - name: Build tunnel pairs
      set_fact:
        tunnel_pairs: "{{ all_tunnels | community.general.json_query('[].tunnels[]') | list }}"

    # ✅ Flattened loop: each task runs individually
    - name: Find remote tunnel
      set_fact:
        remote_tunnel: "{{ tunnel_pairs | selectattr('3', 'equalto', item.1[4]) | list | first }}"
      loop: "{{ all_tunnels | subelements('tunnels') }}"
      loop_control:
        label: "{{ item.0.device }} Tunnel {{ item.1[0] }}"
      vars:
        device: "{{ item.0.device }}"
        tunnel: "{{ item.1 }}"

    - name: Run ping test
      ios_command:
        commands:
          - >-
            {% if tunnel[2] is defined %}
            ping vrf {{ tunnel[2] }} {{ remote_tunnel[5] }} size {{ tunnel[1] }} df-bit repeat 5
            {% else %}
            ping {{ remote_tunnel[5] }} size {{ tunnel[1] }} df-bit repeat 5
            {% endif %}
      delegate_to: "{{ device }}"
      register: ping_result
      when: remote_tunnel is defined
      loop: "{{ all_tunnels | subelements('tunnels') }}"
      loop_control:
        label: "{{ item.0.device }} Tunnel {{ item.1[0] }}"
      vars:
        device: "{{ item.0.device }}"
        tunnel: "{{ item.1 }}"

    - name: Parse ping success
      set_fact:
        ping_status: "{{ 'Pass' if ping_result is defined and 'Success rate is 100 percent' in ping_result.stdout[0] else 'Fail' }}"
      when: remote_tunnel is defined
      loop: "{{ all_tunnels | subelements('tunnels') }}"
      loop_control:
        label: "{{ item.0.device }} Tunnel {{ item.1[0] }}"
      vars:
        device: "{{ item.0.device }}"
        tunnel: "{{ item.1 }}"

    - name: Append row to report
      set_fact:
        report_rows: "{{ report_rows + [ {
          'device': device,
          'tunnel_id': tunnel[0],
          'local_mtu': tunnel[1],
          'local_vrf': tunnel[2]|default('none'),
          'remote_device': remote_tunnel[6]|default('Not Found'),
          'remote_tunnel_id': remote_tunnel[0]|default('N/A'),
          'remote_mtu': remote_tunnel[1]|default('N/A'),
