
import pandas as pd
import plotly.express as px

# Path to the CSV report generated by Ansible playbook
csv_file = '/tmp/tunnel_mtu_report.csv'

# Read the CSV file
df = pd.read_csv(csv_file)

# Validate MTU consistency and summarize ping results
total_tunnels = len(df)
mismatched_mtu = len(df[df['MTU Match'] == 'No'])
failed_pings = len(df[df['Ping Result'] != 'Pass'])

# Summary statistics
summary = {
    'Total Tunnels': total_tunnels,
    'MTU Mismatches': mismatched_mtu,
    'Ping Failures': failed_pings,
    'MTU Match Percentage': round(((total_tunnels - mismatched_mtu) / total_tunnels) * 100, 2),
    'Ping Success Percentage': round(((total_tunnels - failed_pings) / total_tunnels) * 100, 2)
}

print("Summary Report:")
for key, value in summary.items():
    print(f"{key}: {value}")

# Visualization: MTU match vs mismatch
mtu_counts = df['MTU Match'].value_counts().reset_index()
mtu_counts.columns = ['MTU Status', 'Count']
fig_mtu = px.bar(mtu_counts, x='MTU Status', y='Count', title='MTU Match vs Mismatch', color='MTU Status')
fig_mtu.show()

# Visualization: Ping results
ping_counts = df['Ping Result'].value_counts().reset_index()
ping_counts.columns = ['Ping Status', 'Count']
fig_ping = px.bar(ping_counts, x='Ping Status', y='Count', title='Ping Pass vs Fail', color='Ping Status')
fig_ping.show()
