import sys

print("site-list typeA-spokes")
print(" site-id 100-199")
print("!")
print("site-list typeB-spokes")
print(" site-id 200-254")
print("!")

sequence=0
print("control-policy block-typeB-spokes-and-other-hubs")
for siteid in range(100,199):
	sequence+=1
	print("   sequence {}".format(sequence))
	print("    match tloc")
	print("     site-id {}".format(siteid))
	print("     tloc 100.77.{}.1 color public-internet".format(siteid))
	print("    !")
	print("    action reject")
	print("    !")
	print("   !")
	sequence+=1
	print("   sequence {}".format(sequence))
	print("    match route")
	print("     site-id {}".format(siteid))
	print("     tloc 100.77.{}.1 color public-internet".format(siteid))
	print("    !")
	print("    action reject")
	print("   !")
	sequence+=1
	print("   sequence {}".format(sequence))
	print("    match tloc")
	print("     site-id {}".format(siteid))
	print("     tloc 100.77.{}.2 color public-internet".format(siteid))
	print("    !")
	print("    action reject")
	print("    !")
	print("   !")
	sequence+=1
	print("   sequence {}".format(sequence))
	print("    match route")
	print("     site-id {}".format(siteid))
	print("     tloc 100.77.{}.2 color public-internet".format(siteid))
	print("    !")
	print("    action reject")
	print("   !")
	
sequence+=1
print("   sequence {}".format(sequence))
print("    match tloc")
print("     site-list all-hubs")
print("    !")
print("    action reject")
print("    !")
print("   !")
sequence+=1
print("   sequence {}".format(sequence))
print("    match route")
print("     site-list all-hubs")
print("    !")
print("    action reject")
print("    !")
print("   !")
	
sequence=0
print("control-policy block-typeA-spokes-and-other-hubs")
for siteid in range(200,254):
	sequence+=1
	print("   sequence {}".format(sequence))
	print("    match tloc")
	print("     site-id {}".format(siteid))
	print("     tloc 100.77.{}.1 color public-internet".format(siteid))
	print("    !")
	print("    action reject")
	print("    !")
	print("   !")
	sequence+=1
	print("   sequence {}".format(sequence))
	print("    match route")
	print("     site-id {}".format(siteid))
	print("     tloc 100.77.{}.1 color public-internet".format(siteid))
	print("    !")
	print("    action reject")
	print("   !")
	sequence+=1
	print("   sequence {}".format(sequence))
	print("    match tloc")
	print("     site-id {}".format(siteid))
	print("     tloc 100.77.{}.2 color public-internet".format(siteid))
	print("    !")
	print("    action reject")
	print("    !")
	print("   !")
	sequence+=1
	print("   sequence {}".format(sequence))
	print("    match route")
	print("     site-id {}".format(siteid))
	print("     tloc 100.77.{}.2 color public-internet".format(siteid))
	print("    !")
	print("    action reject")
	print("   !")
	
sequence+=1
print("   sequence {}".format(sequence))
print("    match tloc")
print("     site-list all-hubs")
print("    !")
print("    action reject")
print("    !")
print("   !")
sequence+=1
print("   sequence {}".format(sequence))
print("    match route")
print("     site-list all-hubs")
print("    !")
print("    action reject")
print("    !")
print("   !")

print("data-policy typeA-spoke-dscp-preference")
for vpn in range(1,4):
	sequence=1	
	print("  vpn-list VPN{}".format(vpn))
	print("   sequence {}".format(sequence))
	print("    match")
	print("     dscp 2 4 6 8")
	print("    !")
	print("    action accept")
	print("     count low-dscp")
	print("     set")
	print("      tloc-list typeA-dscp-low")
	print("      vpn {}".format(vpn))
	print("     !")
	print("    !")
	print("   !")
	sequence+=1
	print("   sequence {}".format(sequence))
	print("    match")
	print("     dscp 36 38 46")
	print("    !")
	print("    action accept")
	print("     count high-dhcp")
	print("     set")
	print("      tloc-list typeA-dscp-high")
	print("      vpn {}".format(vpn))
	print("     !")
	print("    !")
	print("   !")
	print("   default-action accept")
	print("  !")

print("!")

print("data-policy typeB-spoke-dscp-preference")
for vpn in range(1,4):
	sequence=1	
	print("  vpn-list VPN{}".format(vpn))
	print("   sequence {}".format(sequence))
	print("    match")
	print("     dscp 2 4 6 8")
	print("    !")
	print("    action accept")
	print("     count low-dscp")
	print("     set")
	print("      tloc-list typeB-dscp-low")
	print("      vpn {}".format(vpn))
	print("     !")
	print("    !")
	print("   !")
	sequence+=1
	print("   sequence {}".format(sequence))
	print("    match")
	print("     dscp 36 38 46")
	print("    !")
	print("    action accept")
	print("     count high-dhcp")
	print("     set")
	print("      tloc-list typeB-dscp-high")
	print("      vpn {}".format(vpn))
	print("     !")
	print("    !")
	print("   !")
	print("   default-action accept")
	print("  !")

print("!")
print("data-policy hub-dscp-preference")
for vpn in range(1,4):
	sequence=1	
	print("vpn-list VPN{}".format(vpn))
	for site in range(100,199):
		print("   sequence {}".format(sequence))
		print("    match")
		print("     dscp 2 4 6 8")
		print("     destination-ip 100.74.{}.0/30".format(site))
		print("    !")
		print("    action accept")
		print("     count low-dscp")
		print("     set")
		print("      tloc-list site{}a-dscp-low".format(site))
		print("      vpn {}".format(vpn))
		print("     !")
		print("    !")
		print("   !")
		sequence+=1
		print("   sequence {}".format(sequence))
		print("    match")
		print("     dscp 36 38 46")
		print("    destination-ip 100.74.{}.0/30".format(site))  
		print("    !")
		print("    action accept")
		print("     count high-dhcp")
		print("     set")
		print("      tloc-list site{}a-dscp-high".format(site))
		print("      vpn {}".format(vpn))
		print("     !")
		print("    !")
		print("   !")
		sequence+=1
		print("   sequence {}".format(sequence))
		print("    match")
		print("     dscp 2 4 6 8")
		print("     destination-ip 100.74.{}.4/30".format(site))
		print("    !")
		print("    action accept")
		print("     count low-dscp")
		print("     set")
		print("      tloc-list site{}b-dscp-low".format(site))
		print("      vpn {}".format(vpn))
		print("     !")
		print("    !")
		print("   !")
		sequence+=1
		print("   sequence {}".format(sequence))
		print("    match")
		print("     dscp 36 38 46")
		print("    destination-ip 100.74.{}.4/30".format(site))  
		print("    !")
		print("    action accept")
		print("     count high-dhcp")
		print("     set")
		print("      tloc-list site{}b-dscp-high".format(site))
		print("      vpn {}".format(vpn))
		print("     !")
		print("    !")
		print("   !")
		sequence+=1
	for site in range(200,255):
		print("   sequence {}".format(sequence))
		print("    match")
		print("     dscp 2 4 6 8")
		print("     destination-ip 100.74.{}.0/30".format(site))
		print("    !")
		print("    action accept")
		print("     count low-dscp")
		print("     set")
		print("      tloc-list site{}a-dscp-low".format(site))
		print("      vpn {}".format(vpn))
		print("     !")
		print("    !")
		print("   !")
		sequence+=1
		print("   sequence {}".format(sequence))
		print("    match")
		print("     dscp 36 38 46")
		print("    destination-ip 100.74.{}.0/30".format(site))  
		print("    !")
		print("    action accept")
		print("     count high-dhcp")
		print("     set")
		print("      tloc-list site{}a-dscp-high".format(site))
		print("      vpn {}".format(vpn))
		print("     !")
		print("    !")
		print("   !")
		sequence+=1
		print("   sequence {}".format(sequence))
		print("    match")
		print("     dscp 2 4 6 8")
		print("     destination-ip 100.74.{}.4/30".format(site))
		print("    !")
		print("    action accept")
		print("     count low-dscp")
		print("     set")
		print("      tloc-list site{}b-dscp-low".format(site))
		print("      vpn {}".format(vpn))
		print("     !")
		print("    !")
		print("   !")
		sequence+=1
		print("   sequence {}".format(sequence))
		print("    match")
		print("     dscp 36 38 46")
		print("    destination-ip 100.74.{}.4/30".format(site))  
		print("    !")
		print("    action accept")
		print("     count high-dhcp")
		print("     set")
		print("      tloc-list site{}b-dscp-high".format(site))
		print("      vpn {}".format(vpn))
		print("     !")
		print("    !")
		print("   !")
		sequence+=1
	print("  !")
	print("  default-action accept")
	print(" !")

print("lists")
for siteid in range(100,199):
	print("  tloc-list site{}a-dscp-low".format(siteid))
	print("   tloc 100.77.{}.1 color public-internet encap ipsec preference 3".format(siteid))
	print("   tloc 100.77.{}.1 color private3 encap ipsec preference 2".format(siteid))
	print("   tloc 100.77.{}.1 color private1 encap ipsec preference 1".format(siteid))
	print("  !")
	print("  tloc-list site{}a-dscp-high".format(siteid))
	print("   tloc 100.77.{}.1 color public-internet encap ipsec preference 1".format(siteid))
	print("   tloc 100.77.{}.1 color private1 encap ipsec preference 2".format(siteid))
	print("   tloc 100.77.{}.1 color private3 encap ipsec preference 3".format(siteid))
	print("  !")
	print("  tloc-list site{}b-dscp-low".format(siteid))
	print("   tloc 100.77.{}.2 color public-internet encap ipsec preference 3".format(siteid))
	print("   tloc 100.77.{}.2 color private3 encap ipsec preference 2".format(siteid))
	print("   tloc 100.77.{}.2 color private1 encap ipsec preference 1".format(siteid))
	print("  !")
	print("  tloc-list site{}b-dscp-high".format(siteid))
	print("   tloc 100.77.{}.2 color public-internet encap ipsec preference 1".format(siteid))
	print("   tloc 100.77.{}.2 color private1 encap ipsec preference 2".format(siteid))
	print("   tloc 100.77.{}.2 color private3 encap ipsec preference 3".format(siteid))
	print("  !")
  
for siteid in range(200,254):
	print("  tloc-list site{}a-dscp-low".format(siteid))
	print("   tloc 100.77.{}.1 color public-internet encap ipsec preference 3".format(siteid))
	print("   tloc 100.77.{}.1 color private4 encap ipsec preference 2".format(siteid))
	print("   tloc 100.77.{}.1 color private2 encap ipsec preference 1".format(siteid))
	print("  !")	
	print("  tloc-list site{}a-dscp-high".format(siteid))
	print("   tloc 100.77.{}.1 color public-internet encap ipsec preference 1".format(siteid))
	print("   tloc 100.77.{}.1 color private2 encap ipsec preference 2".format(siteid))
	print("   tloc 100.77.{}.1 color private4 encap ipsec preference 3".format(siteid))
	print("  !")
	print("  tloc-list site{}b-dscp-low".format(siteid))
	print("   tloc 100.77.{}.2 color public-internet encap ipsec preference 3".format(siteid))
	print("   tloc 100.77.{}.2 color private2 encap ipsec preference 2".format(siteid))
	print("   tloc 100.77.{}.2 color private4 encap ipsec preference 1".format(siteid))
	print("  !")
	print("  tloc-list site{}b-dscp-high".format(siteid))
	print("   tloc 100.77.{}.2 color public-internet encap ipsec preference 1".format(siteid))
	print("   tloc 100.77.{}.2 color private2 encap ipsec preference 2".format(siteid))
	print("   tloc 100.77.{}.2 color private4 encap ipsec preference 3".format(siteid))
	print("  !")  
  


